version: '3'
services:
  clock-bot:
    container_name: clock-bot
    build: .
    hostname: clock-bot
    volumes:
      - .:/usr/src/app
      - ./config:/usr/src/app/config
      - ./log:/usr/src/app/log
    command: bash -c "python -u main.py"
